[book]
authors = []
language = "en"
multilingual = false
src = "src"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[build]
build-dir = "book/html"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
#theme = "rust"
#default-theme = "dark"
#preferred-dark-theme = "ayu"

#[output.markdown]

